BASE = ../rai

ROS = 1
OPENCV = 1

OBJS = main.o vision.o board.o kinematic.o kinmodel.o controller.o gamelogic.o

DEPEND = Geo Kin Core Gui RosCom Operate Perception 

include $(BASE)/build/generic.mk